message:
  login:
    error: "登录失败，可能是密码不正确哦"
    success: "登录成功"
  register:
    error: "注册失败,可能是密码不符合要求!"
    success: "注册成功"
  empty: '不能提交空密码!'
  reload: "配置文件已刷新!"
setting:
  #注册完后是否自动登录?
  register_auto_login: true
  #Gui or Chat 两种类型 分别是 聊天直接发 与 铁砧GUI
  type: chat
  #Gui界面的btn材质
  gui:
    button_item_material: APPLE