name: AuthLogin
version: 1.0.0
main: cc.mcyx.AuthLogin
author: Zcc (星兮兮)
api-version: 1.20
folia-supported: true
depend:
  - AuthMe

commands:
  GuiLogin:
    description: "GUI快捷登录"
    permission: "GuiLogin.admin"
    permission-message: "你没有权限呢?"