name: FastAuth
version: '${project.version}'
main: cc.mcyx.FastAuth
author: Zcc (星兮兮)
api-version: 1.20.1
folia-supported: true
description: "只为更快登录而生!"
depend:
  - AuthMe
  - ProtocolLib
commands:
  FastAuth:
    description: "FastAuth 重载配置命令"
    permission: "fastAuth.admin"
    permission-message: "你没有权限呢?"