name: FastLogin
version: ${project.version}
main: cc.mcyx.FastLogin
author: Zcc (星兮兮)
api-version: 1.13
folia-supported: true
depend:
  - AuthMe
  - ProtocolLib
commands:
  GuiLogin:
    description: "GUI快捷登录"
    permission: "GuiLogin.admin"
    permission-message: "你没有权限呢?"