name: FastAuth
version: ${project.version}
main: cc.mcyx.FastAuth
author: Zcc (星兮兮)
api-version: 1.13
folia-supported: true
depend:
  - AuthMe
  - ProtocolLib
commands:
  FastAuth:
    description: "FastAuth 重载配置命令"
    permission: "fastAuth.admin"
    permission-message: "你没有权限呢?"